language: python
os:
- linux
python:
- 3.6
cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
before_install:
- sudo apt-get update
- sudo apt-get -y install python3-pip
- sudo apt-get install python3-setuptools
- sudo pip3 install awscli
install:
- pip install $(cat requirements.txt $(find lib -name requirements.txt | sort) | sort
  | uniq | sed 's/ *== */==/g')
- pip install -r requirements-dev.txt
script:
- "./test.sh"
after_success:
- codecov
deploy:
- provider: script
  script: bash ./.travis/build-deploy.sh test us-east-2
  on:
    branch: master
notifications:
  email: false
env:
  global:
  - secure: ThyRUZCQQlzUIl9PzuEAsebdEfiBPTaq6G8hz8U32iDvKLBK1udy1GvaheDhtEmgG0RGQFokO3VxWc31z1dZN6uLMHdcZcEdF3Mc1RpSpTRr+8fuWL00mrO9wxNqPYfEGqi0QVca7Aa+QMQCUHtJDuyhBaX2JiXixbEkAGtjTaPdvoYjaxtz1oFRdL/Uilvt7R8xSjBLzjxU8pPfNGMH9rEozUMBPntqKij2aUcyEiXfjCoEydGz5SLl6rbZH/zwM3fSQk8YrbyQsCzuy+HO0hysIyH6qvEfb+LurbeYv4mj6zW+boxBSynxreb3jJyt5Pe3mNFzWaYRrFJNGBafGPeCSbVZYVvD78wbsL7xyz2f+N2LQPq2Z1I9n8Gpq1C1tRDuvpYW7jhBN7OsQJI4lMIPor3xU8WQtLGtM3bCjlrQ3OQfZaqBHdaUTKdnG3sK9w6wjdZkEJT2ACApGqvS7QKCOjlDVHyFvYKvW12vhH4d5FClDxVp7zLnTZjGrYaqgp6QiBttJwV3bqOLLSwCMAtRBH0hLYve8JfC4K3VtsG3zqCz6cTyv8RryMyuUlorucuLwD+Sc3seySw8gzWVooeTdNB9UsxGC/k75A007lnolUWyts1eDW9yvqvAJycndfpRETVAjrcw6x+X11gvki0AFy1QXJH90yoX+WSZ7SA=
  - secure: d6LrDznabclt277uTAnIpE3ee1HXuNAMHZ2sjDIBOpOEwYMX2y917iYgbs432L+mwCjVeWxpiqBtHaXdRL6Z+FuFMvMLYJcXVkOTytVGxvtmlngD5amJayOEeUxxiB/iNI8BJS1p1yC9HaSTfz6+xMW0bvVHWMyp+LqUq6Ay/mpRvYABbN81yrmbeOOe3E61eFl7U01OVDJfStHpLufSSpniHLGkoxLEDA12P6B6oqC4zp6JiC/t9WDu40FYzRDBpcdPOjDKYfyhl7/RMOl0OJXnbf27w/bxoQCgOLyLT9BLGOEL/ueeB+H68xlfkIEzo1ybUyP1q5jkYEh4wlHqc/eIWsgGsr3dsVt6OYLm8nSryaaCQukEyhvbCIUhlyqVLeEW1ygz0b7szCjiwO+9RGSuVp7U0OKdinzz/edB3e6H4gPP7v45nWnUK6ccpMqiQVBw7uzYlobjL+ENSxPDNcgutDPdaCahq/2EaUpHg5PY1S384mBfJU8yjjLNBDVbv+ewvjEj2lDf9gxb7XHFPyxwRTxbm50GzAPzsrb1ncN7Ub2P+A5CNURRvnS/KJI/Efl1aSB0Ed3xcEFsXcU9H2o0oUItIFlyz+2QFaZNvvWS4KtVSkZUjMasbt6TxqGDzze7DHvf2+CZZY5sqhbmKXT1cZ69b+pjTVLEXTwjDBw=
