language: python

os:
- linux

python:
- 3.6

services: docker

cache: pip

before_cache:
- rm -f $HOME/.cache/pip/log/debug.log

before_install:
- sudo apt-get update
- sudo apt-get -y install python3-pip
- sudo apt-get install python3-setuptools
- sudo pip3 install awscli

install:
- pip install $(cat requirements.txt $(find lib -name requirements.txt | sort) | sort
  | uniq | sed 's/ *== */==/g')
- pip install -r requirements-dev.txt

script:
- ./test.sh

after_success:
- codecov

deploy:
  provider: script
  script: ./.ci/docker_push.sh
  on:
    branch: master
