language: python
os:
- linux
python:
- 3.6
cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
before_install:
- sudo apt-get update
- sudo apt-get -y install python3-pip
- sudo apt-get install python3-setuptools
- sudo pip3 install awscli
install:
- pip install $(cat requirements.txt $(find lib -name requirements.txt | sort) | sort
  | uniq | sed 's/ *== */==/g')
- pip install -r requirements-dev.txt
script:
- "./test.sh"
after_success:
- codecov
deploy:
- provider: script
  script: bash ./.travis/build-deploy.sh prod us-east-1
  on:
    branch: master
notifications:
  email: false
env:
  global:
  - secure: NE/h7WZdA2bE/BFMFNXDWypHp29qsvMFQi9SCRvfZxte3o85eYYzd/g259gaIr2uPDUI8/qfCbq2OXlvdeqziAgfe/SjDwOZv4suXfJkA/nRfV6vhkj4TsiNBtorw80MwDWENnjuUN8O/f483qXk4AUd4fxDfsMG3PBOOjEUEbyeb2Me8xxyXk/JlpHidGLzgntpBKcsHDJjEgv9EwgeMvDMA3GglXaftWR/XJ4ESLLYRRP1paTWo9v2qWTwvozF7dEZzH6cEZgNxUihSVLwlmoliH1quHATKPv4j6NGC2t1qLA0SaJ8Jk01i+13UdF9p9f4TV8Qa997RB9ffkk7O2dCAdhjyeteQbRJ3JJLQHIebUu6z/2b58al9r4rGt84bN9elyz59AxWayRw++1fJSrSgzDPv9kL/wkYnOyHNvFic5ofZbUFElcxln4ZdJypMMjnYC6A91RrPWqHvu6Ms7LmtgscLjcjf031S6ns52w1uY9HoJ4zXNVflZduwfb16VD1qNVa9um1iRrvl2ZsaseMK1BbqTJh1fEydrTC2VoSO21QAZ2S26UpcMAjuxSHBy8j1cTMEGuersqccJmeNrNFz6CWP3qLa1lbLqE+Aw5Oac515ijJs/+1n51q8BiTJovGc4OY45UcCBbGx8yUBm6iQyl16GI7Gzc2MWxTV+I=
  - secure: IK+XhaIlWYxGOD2lzDIpkVbC4Dn41XVqU5vOjNdOHDK6YpFr/AXK2usfd8rN+RXewOmMKDURKjlhSU7X9oXUb72nFwRsg3I0hXfjOt/+MykxSDOfBEeyRXR0UCEUb2u22N40V8GPmU7Apk+6o/GFnyFLJSGPmNzfTkQv9qk2lHG7yPe3B6yb+FHPCTNvSETEAASbuoUIWnQ5HQysyPOP65wUoA5KxlYvhLraqH/VC/DXnCfrwEtLL5uP401X5RgK342EFGkbHiGPg+eJCgF3tLuzvKpiVIdijzAA5FZ69KPp01nTJQIErBvt04MuxG351CsEFrqKdOO4cEgJ/Z4ynSP46Ks+SivGI/aBfDdB85z1cGlVjKZJimnoZs2qQbsx0X/rIDWHUM9PzYGCaSHY3aCNFXnxyYnan2BwJrza1kWh9pjirXDTMeZRs6DmbJYPrW8BZveBt+Nctok9kNuaG0YXedeh0/qri7IaeH5dexf8mGaR+fhPCbJveGzRIUEqyDUVEsULDXowqGOjdlAxFxXzYXtv9ZPxEyVBWavHTLIfKbP8EW2fV3U3LNdJDsqaXyjrx6Sy/0OxFnH1pjGzr1tXE4wShJBmqYp4vbF0LUPOdBI0cfW+5N6tBXeyDXSDpCC479DIFsg7fCZqNDtVoFOuN+WM/b25hkmEFR/YAQU=
